Repository Meet-with-Me/monorepo, pull requests merged in 2020-11, with the labels that each got.

#1 Run create-react-app
  README.md
  meet-with-me/.gitignore
  meet-with-me/README.md
  meet-with-me/package-lock.json
  meet-with-me/package.json
  meet-with-me/public/favicon.ico
  meet-with-me/public/index.html
  meet-with-me/public/logo192.png
  meet-with-me/public/logo512.png
  meet-with-me/public/manifest.json
  meet-with-me/public/robots.txt
  meet-with-me/src/App.css
  meet-with-me/src/App.js
  meet-with-me/src/App.test.js
  meet-with-me/src/index.css
  meet-with-me/src/index.js
  meet-with-me/src/logo.svg
  meet-with-me/src/reportWebVitals.js
  meet-with-me/src/setupTests.js
  package-lock.json
  package.json
Labels: front-end

#2 Create server and connect to meet-with-me DB
  server/.git-ignore
  server/package-lock.json
  server/package.json
  server/server.js
Labels: back-end, reviewed

#3 Create initial user and session schemas
  server/models/session.model.js
  server/models/user.model.js
Labels: back-end, reviewed

#4 [Client] Add client router
  meet-with-me/package-lock.json
  meet-with-me/package.json
  meet-with-me/public/favicon.ico
  meet-with-me/public/logo192.png
  meet-with-me/public/logo512.png
  meet-with-me/src/App.css
  meet-with-me/src/App.js
  meet-with-me/src/App.test.js
  meet-with-me/src/app.js
  meet-with-me/src/index.js
  meet-with-me/src/logo.svg
  meet-with-me/src/scenes/__tests__/about.test.js
  meet-with-me/src/scenes/__tests__/dashboard.test.js
  meet-with-me/src/scenes/__tests__/home.test.js
  meet-with-me/src/scenes/__tests__/oops.test.js
  meet-with-me/src/scenes/about.js
  meet-with-me/src/scenes/dashboard.js
  meet-with-me/src/scenes/home.js
  meet-with-me/src/scenes/oops.js
Labels: front-end, ready-for-review

#5 [Client] Add logging in with Google
  meet-with-me/package-lock.json
  meet-with-me/package.json
  meet-with-me/src/app.js
  meet-with-me/src/hooks/__tests__/.keep
  meet-with-me/src/hooks/use-login.js
  meet-with-me/src/hooks/use-logout.js
  meet-with-me/src/utils/refresh-google-token.js
Labels: front-end, ready-for-review

#6 [Client] Update app name and icon
  meet-with-me/public/icon.ico
  meet-with-me/public/index.html
  meet-with-me/public/m.jpg
  meet-with-me/public/manifest.json
Labels: front-end, ready-for-review

#8 [Server] P hubbell google auth login endpoint
  server/models/user.model.js
  server/package-lock.json
  server/package.json
  server/routes/user.route.js
  server/server.js
Labels: back-end, ready-for-review

#7 [Client] Phubbell static dashboard scene
  meet-with-me/package-lock.json
  meet-with-me/package.json
  meet-with-me/public/index.html
  meet-with-me/src/components/css/session-card.css
  meet-with-me/src/components/session-card.js
  meet-with-me/src/index.css
  meet-with-me/src/index.js
  meet-with-me/src/scenes/css/dashboard.css
  meet-with-me/src/scenes/dashboard.js
Labels: front-end, ready-for-review

#9 Add prettier config file to git ignore
  .gitignore
Labels: ready-for-review

#11 [Client] Create profile context
  meet-with-me/src/contexts/profile-context.js
  meet-with-me/src/index.js
  meet-with-me/src/scenes/home.js
Labels: front-end, ready-for-review

#10 [Client] Fix routing from session card
  meet-with-me/src/components/session-card.js
Labels: front-end, ready-for-review

#12 [Client] Phubbell client login post to server
  meet-with-me/src/hooks/use-login.js
  meet-with-me/src/server.js
  server/routes/user.route.js
Labels: front-end, ready-for-review
